### ISSUE TITLE
psexec_scanner.rb bombs out

### ISSUE THREAD

**Issue by akiraowen** [darkoperator/Meterpreter-Scripts#7]
When I went to use the scanner on Kali 2020.2 msf5 the code fails to find the workspace name:

- Auxiliary failed: NoMethodError undefined method `name' for nil:NilClass
 - Call stack:
-   /home/kali/.msf4/modules/auxiliary/scanner/smb/psexec_scanner.rb:226:in `create_multihand'
-   /home/kali/.msf4/modules/auxiliary/scanner/smb/psexec_scanner.rb:77:in `setup'

**Comment by akiraowen** [comment]
I patched with "mul.datastore['WORKSPACE'] = framework.db.find_workspace(self.workspace)"
